spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LearnSpringBoot
    username: postgres
    password: Mendax47
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.web: error
    org.springframework.security: error
    org.hibernate.sql: error